# Quality of life component. A built-in time module for time-related functionality and delays. It makes the text pop a bit more too.
import time

# Quality of life component. A built-in module to wrap onscreen text. There'll be no unintentional garbled space transmissions.
import textwrap

def wrap_text(text):
    wrapped_text = textwrap.fill(text, width=150)
    print(wrapped_text)


# This part took a lot more time than I'll ever admit.
def intro():
    time.sleep(0.5)
    print("")
    print("Nathan D Strzelczyk presents...")
    print("")
    time.sleep(0.5)
    print("A Code In Place Final Project...")
    print("")
    time.sleep(0.5)
    print("")
    print("------------------------------------------------------------------------")
    print("------------------------------------------------------------------------")
    print("-                                   !                                  -")
    print("-  !     !                        !!!!!                                -")
    print("-  #\    # ! !!!!! !!!!!   !!!!  !  ^  ! !!!!!    !!   !!!!!  !!!!!!!  -")
    print("-  # \   # #   #   #    \ #    \ #  ^    #    \  #  \  #    \ #        -")
    print("-  #  \  # #   #   #    / #    # #  ###\ #    / #    \ #    # #######  -")
    print("-  #   \ # #   #   ####/  #   \# #  ^  # #/##/  ###### #    # #        -")
    print("-  #    \# #   #   #   \  #    # #  ^  / #   \  #    # #    # #        -")
    print("-  #     # #   #   #    \  #### \ ##### /#    \ #    # ####/  #######  -")
    print("-                                \  ^  /                               -")
    print("-                                 \ ^ /                                -")
    print("-<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< X >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-")
    print("-           A Choose Your Own Space-Venture Python Text Game           -")
    print("-                                /  v  \                               -")
    print("------------------------------------------------------------------------")
    print("------------------------------------------------------------------------")
    print("")
    print("")

intro()

# If I wrote this whole thing right, seeing this part should get old.
print("")
wrap_text("Welcome to an adventure. This is a Choose Your Own Adventure-style game written in Python. You choose what happens, so choose wisely.")
print("")
wrap_text("The adventure before you is set in space, a timeless place full of the most vibrant of brights and the deepest of darks. In every direction, all around you, is endlessness.")
print("")
wrap_text("Your mission: to deliver all important cargo across the expanses and to the farthest reaches of space. You know the risks just as well as you know the rewards.")
print("")
wrap_text("It's now 0500 XST. Time to start your day.")
print("")
time.sleep(1)
input("Press the ENTER to continue...")
print("")


def choose_destination():
    print("")
    wrap_text("The computer screen before you lights up and scalds your eyes with brightness, jarring you abruptly from the quiet darkness. You shield your eyes from the sudden light, but equally from perhaps the most ugly combination of white and green in the entire universe. As your eyes adjust, you see three deliveries for today. 'This should be easy,' you think before quickly correcting yourself with, 'It WILL be easy.' It's mind over matter, after all. You go with your gut and make your selection.")
    print("")
    time.sleep(1)
    print("1. Planet Caseus III")
    print("")
    print("2. Amelia Research Station (WIP)")
    print("")
    print("3. Lamb-Harlon Corporation Mining Outpost 33H5N48 (WIP)")
    print("")
    choice = input("The computer screen awaits your response, and it'll wait forever if you let it. Enter the number of your chosen destination: ")
    print("")
    
    if choice == '1':
        caseus_iii()
    elif choice == '2':
        amelia_station()
    elif choice == '3':
        mining_outpost()
    else:
        print("")
        print("The screen flashes red and beeps deeply, almost angrily. 'Butter fingers,' you think. 'I should try that again, but better this time.'")
        print("")
        input("Press the ENTER to continue...")
        print("")
        choose_destination()


# Amelia Research Station.
def amelia_station():
    print("")
    wrap_text("'Amelia Research Station: selected,' the male computer voice reads in its pleasant monotone voice. The engines hum to life before rocketing you, your ship, and its cargo off towards your destination, seemingly in that very order. FTL is fast like that.")
    print("")
    wrap_text("'Arriving... arrive... arrive... : the...,' the male computer voice trails off, static fizzing up lightly before cutting off, seemingly completing the announcement. Your eyes perk up questioningly. 'That's not weird at all,' you think, hoping to convince yourself that a glitch like that just so happened to happen now, here, at this place. You lean forward and peer outward, cautiously taking in the bright nothingness at your destination. Outside your ship is the blinding white light from countless stars, clustered together in such a way that no shadows could ever exist here. 'No shadows for any space monsters to hide out in at least,' you think but equally hope. But this knowledge does nothing to reassure you against what you're feeling - there's just a foreboding unease here.")
    print("")
    wrap_text("Squinting, you see a singular grayish shape ahead amidst the pure sunlight - the Amelia Research Facility, positioned here to gather data on the Minor Bottle Star Cluster, more often known as the Dread Springs.")
    print("")
    wrap_text("This is still a work in progress, and there's currently nothing else here.")
    print("")
    time.sleep(1)
    print("")
    input("Press the ENTER to continue...")
    print("")
    choose_destination()


# Lamb-Harlon Corporation Mining Outpost 33H5N48.
def mining_outpost():
    print("")
    wrap_text("'Lamb-Harlon Corporation Mining Outpost 33H5N48: selected,' the male computer voice reads in its pleasant monotone voice. The engines hum to life before rocketing you, your ship, and its cargo off towards your destination, seemingly in that very order. FTL is fast like that.")
    print("")
    wrap_text("'Arriving: Lamb-Harlon Corporation Mining Outpost 33H5N48,' the male computer voice announces. You lean forward to peer outward, taking in the outpost's growing size as your ship approaches. However, something immediately strikes you as unusual - there were no approach comms, and there's no visible activity from the station. Oddly, the normally bustling outpost appears eerily quiet today. As your ship draws closer, you notice several other ships docked at the outpost. This isn't unusual by itself, but coupled with the other observations, you begin to consider turning your ship around and leaving. 'It'd be the smart move to just leave now,' you begin to think, 'but I'm already here, so the job is pretty much already done.' You slow your approach to better take in the situation. The lights that typically illuminate the station are mysteriously off, casting a shadowy gloom over the docked ships and the outpost itself. 'I just need to make my delivery and go. That's all I have to do,' you reassure yourself, and correctly, as technically no one has to sign for this particular delivery. There's no need to go looking around here for anyone, or anything for that matter. Just drop off delivery and leave.")
    print("")
    wrap_text("This is still a work in progress, and there's currently nothing else here.")
    print("")
    time.sleep(1)
    print("")
    input("Press the ENTER to continue...")
    print("")
    choose_destination()


# Planet Caseus III.
def caseus_iii():
    print("")
    wrap_text("'Planet Caseus III: selected,' the male computer voice reads in its pleasant monotone. The engines hum to life before propelling you, your ship, and its cargo off towards your destination, seemingly in that very order. FTL is fast like that.")
    print("")
    wrap_text("'Arriving: Planet Caseus III,' the male computer voice announces. You lean forward and peer outward, taking in the planet's growing size as your ship approaches. 'It's... very green,' you think, the planet's completely green landscape appearing striking and unnatural. Planet Caseus III, the product of extensive terraforming, is unapologetically manmade and made with a singular purpose in mind: milk production, but namely and more namesake, cheese production. Here, the best cheeses in the entire universe are made.")
    print("")
    wrap_text("You land at the given coordinates, a building painted like a red-and-white barn from Earth 1, and then exit your ship to find someone to sign for the delivery. As you begin to walk towards the building, you see a robot exit the structure from the front and begin speeding towards you. This briefly stops you in your tracks, but its waving hand relieves some of your initial tension. And more disarmingly, the robot appears to be dressed in blue overalls and a straw hat. 'Murderous robots don't generally dress like that,' you think before pausing again to consider the thought further. The farming robot slows and then stops before you, appearing to be awaiting a response.")
    print("")
    time.sleep(1)
    input("Press the ENTER to continue...")
    print("")
    print("You're in the right place. Now, to make the right choice.")
    print("")
    print("1. Introduce yourself to the farming robot and state your purpose here.")
    print("")
    print("2. Order the farming robot to unload your ship's cargo.")
    print("")
    print("3. Walk past the farming robot to enter the building as planned.")
    print("")
    choice = input("Enter the number of your choice: ")
    print("")

    if choice == '1':
        print("")
        wrap_text("'Hi,' you begin as you address the farming robot, 'I'm here to make a delivery...?' You can't help but trail off into a questioning tone. The farming robot does not immediately respond. You wonder if this robot even understands human speech. Being a farming robot, can it even hear you? Do farming robots even need ears? 'WELCOME. PLEASE FOLLOW,' the farming robot abruptly states in a very robotic voice, cutting off your thoughts in surprise. You follow the farming robot to the right side of the building, and as the interior lights turn on, you see what appears to be an empty warehouse area. As you take in the area, the robot signs your paperwork within half a seconds time, and perfectly despite the clipboard being upside down. You open your mouth briefly to say something but don't, remaining at a loss for words as this encounter continues.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_1()
    elif choice == '2':
        print("")
        wrap_text("'Unload my ship's cargo, robot, and make it snappy,' you bark at the farming robot. The farming robot remains motionless, appearing to not understand your command. This frustrates you, but before you try saying a different command, the robot speeds around you towards your ship. You smile smugly and cross your arms. 'I knew this was gonna be an easy one,' you briefly think before the farming robot tears off your ship's cargo bay door. You take a step to run towards your ship to order the robot to stop, to turn off, to anything other than what it's doing but you trip over yourself in a panic and crash to the ground. As you stand, another robot bumps into you as it passes by, knocking you down again. And then another one. Glancing up briefly, you see countless farming robots speeding towards your ship from all directions. In the hopes that it'll be enough, you curl up in a ball on the ground to guard yourself. The thundering of robots arriving at your position and your ship continues all around you for several minutes.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_2()
    elif choice == '3':
        print("")
        wrap_text("You relax and smile at the farming robot, shaking your head as you keep walking towards the building. This is a farming robot, and not a shipping robot, or a delivery robot, or any kind of robot that could help you, so there's no need to waste any time with it. The farming robot follows you, remaining at your side as you continue walking towards the building. You wave it away as you order it, 'Return to duties, or whatever it is that you do. Go away!' The farming robot slows and then stops, watching you briefly as you begin to enter the front of the building before returning to its duties.")
        print("")
        print("Six months later...")
        print("")
        wrap_text("'And now, let's talk about safety.' In a nearly empty conference room, dimly lit for viewing purposes, a training video played against the wall from an overhead projector. On the screen, a narrator discussed the 'do's and don'ts' of making deliveries to locations without people, places that are entirely run by computers and machinery. '...these places are safe for the robots that work there because those places were designed with them in mind. A robot doesn't have to worry about getting his hands caught in machinery because oftentimes, his hands are supposed to go there by design.' The video continues showing several robots fitting inside of and then moving around a room with seemingly dozens of moving parts, belts, and presses, effortlessly and without issues. 'If a person were to enter one of these places, they'd likely end up somewhere across every surface in here in a matter of seconds, and no one wants that.' The video continues by discussing the importance of customer service when making deliveries.")
        print("")
        time.sleep(1)
        wrap_text("You've achieved ending 3 of 7 after finding your end on Planet Caseus III and your way into a poorly animated 3D safety briefing, and even into some product according to the recall.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        restart_game()
    else:
        print("")
        print("That doesn't appear to be an option here. I should go over all of this again.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        caseus_iii()


def continue_adventure_1():
    print("")
    wrap_text("'UNLOAD HERE,' the robot states robotically. This large red-and-white building appears to be a complete facility in itself, having everything a dairy farm would need under one roof. It'd only make sense that it'd also have a warehouse area. You begin to wonder what the front side entrance was for, but you have a job to do now - time to get unloaded. Looking around the warehouse area, you see a forklift that'll be very helpful in unloading all of these pallets. You don't recall exactly what you were hauling here, but you do remember that it was packaged securely. You go to check the manifest.")
    print("")
    wrap_text("106 pallets. The word 'Water' can be made out on the printed on the document but not much ink made it to the page. 'I'll have to change the printer ink when I get a chance,' you think. You consider the idea of delivering water here and think that it makes sense. A dairy farm would need water, and you didn't see any bodies of water on your approach. You scratch your head as you think about it. 106 pallets of water doesn't seem like it'd be enough for a facility of this size though, but maybe they recycle. 'Yeah,' you think, 'that's probably it.'")
    print("")
    wrap_text("You get on the forklift and return to your ship to begin unloading. 'After this first one, I'll just 105 more pallets to go,' you absently think as you position the forklift in front of the first pallet, picking it up from your cargo bay with ease. Reversing out, you then return to the warehouse before pausing in front of the side entrance. Though this warehouse area is big, it appears to be divided into two different sections, with the floors being marked to further indicate this. You notice that on both sides of the floors and on the walls that there are QR codes.")
    print("")
    wrap_text("The codes look very similar to you, and they may even be the same code. You squint to see them better from your position on the forklift but to no avail. 'Of all days to forget my glasses at home,' you think, half serious and half joking. Looking around, the farming robot is nowhere in sight, and you do have other deliveries to make today. 'I got this,' you say to yourself as consider what to do.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    print("You're in the right place. Now, to make the right choice.")
    print("")
    print("1. Wait for help because you're uncertain of what to do.")
    print("")
    print("2. Unload the pallets in the area on the left.")
    print("")
    print("3. Unload the pallets in the area on the right.")
    print("")
    choice = input("Enter the number of your choice: ")
    print("")

    if choice == '1':
        print("")
        wrap_text("The forklift hums without purpose as you lean back, waiting and doing nothing. Waiting seems like such an odd choice in this situation, but you don't want to put the pallets down in the wrong spot, or worse, in the spot where other things go. That might cause some issues here, and even more so with these farming robots who don't appear programmed for much else besides what they were designed for.")
        print("")
        wrap_text("You take a deep breath and can't help but notice how great the air smells here. Like, really, really great! You take another deep breath, taking it all in as you do. Even the scenery here is breathtaking. The bountiful green hills are all around you, and looking up at the white clouds above, they seamlessly mix with the blues of the sky as they float by lazily. You adjust yourself in the seat as you continue to wait, your forklift humming along in it's perfect and steady tune. It's so quiet and peaceful here. You begin to worry that you might fall asleep because of all of this, which you eventually do.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_1_1()
        print("")
    elif choice == '2':
        print("")
        wrap_text("You decide to unload the pallets to the left side of the warehouse area. You briefly wonder what goes on the right side, but it's a fleeting thought as you grab the forklift and get started. You get into a good rhythm and begin to make great time. You even begin to literally whistle while you work! Pallet after pallet are unloaded from your ship into the warehouse towards the left side.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_3()
        print("")
    elif choice == '3':
        print("")
        wrap_text("You decide to unload the pallets to the right side of the warehouse area. You briefly wonder what goes on the left side, but it's a fleeting thought as you grab the forklift and get started. Immediately though, the rhythm just isn't there, and you begin to get frustrated at the forklift's slow speed, likely set with safety in mind. 'This. Is. So. SLOW!' you exclaim angrily, hitting the forklift's console. Surprisingly though, the hit causes the console box open up, revealing the maintenance panel underneath it. Your eyes widen in tune with your grin.")
        print("")
        wrap_text("Everything about this forklift can be adjusted through this panel - the speed, the power, everything. Wanting to get done quickly, you set everything to the max. You've driven forklifts before and know what you're doing. The panel beeps with every button push as the settings are turned up to their limit. You close the console cover, confident that these new settings will do the trick. You turn it on and immediately feel the new power beneath you. 'And a trick they'll do,' you think, inaccurately.")
        print("")
        wrap_text("You continue where you left off: picking up a pallet to get it off your ship, but the moment you turn to exit your cargo bay, you're suddenly hurled off across the floor, crashing into the adjacent wall. Dazed, you look up at the forklift, now spinning violently on its back wheels. The settings you put in were definitely to the maximum. You begin to scurry out of the hanger to reach safety, resigning instead to just escape and wait elsewhere, somewhere far safer, for the forklift to run out of juice. Trying anything now would just be too dangerous. The crashing inside of the ship's cargo bay peaked briefly before it careened past you into the engine room and towards your n-fusion power cell. 'Oh-,' you manage to think before the overclocked forklift pierced its cell's housing.")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        wrap_text("You've achieved ending 5 of 7 after having a blast on Planet Caseus III. The cost of the forklift was deducted posthumously.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        restart_game()
    else:
        print("")
        print("That doesn't appear to be an option here. I should go over all of this again.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_1()


def continue_adventure_1_1():
    print("")
    wrap_text("'UNLOAD HERE,' a robot states robotically, its words startling you awake and nearly causing you to lose your balance and fall. You catch the forklift's roll bar just in time, blinking and looking around as you awake. In front of you now stands the farming robot from earlier, or at least another one dressed exactly like it. Looking past it, you see that the warehouse is no longer empty. On the left side now sit over a hundred pallets of what appears to be milk. You rub your eyes as you hop off the forklift and approach the very orderly stacks inside.")
    print("")
    wrap_text("'UNLOAD HERE,' the robot states again. It doesn't gesture, but the area that's empty can be safely assumed to be what it's referring to. But just to be safe, while pointing at the QR code on the right side, you ask, 'What does this code mean?' The robot doesn't immediately respond. Shortly though, it does respond. 'WATER,' the robot answers. 'And what about the other one?' you ask, gesturing at the wall where one of the QR codes was but is now completely blocked by a stack of pallets. The robot turns slightly towards where you gesture before approaching the stack. Without any strain whatsoever, the robot suddenly lifts up three of the pallets to look at the wall behind them, revealing the QR code. The robot pauses again before stating, 'MILK.' 'Well, then it's a good thing that I waited. That could have gone badly,' you say as you rub your head and hop back up onto the forklift. The farming robot does not respond, only returns the pallets carefully to their exact previous position, speeding off around the corner after it does so.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    wrap_text("As you finish unloading your ship, the heat and humidity of this planet becomes increasingly noticeable to you. Beads of sweat form on your forehead, and worst of all, you've already finished your 256 oz Galaxy Gulp, leaving you longing for a refreshing drink of any kind. Looking around, you can't find water anywhere outside, and there's no sign of water in the warehouse either. You think that the absence of water seems odd for a facility dedicated to dairy production, so it must be around here somewhere. Perhaps they have a separate storage area for it. You then remember the shipping manifest - you're the one bringing the water! You playfully tap your head as you approach one of the water pallets in the warehouse.")
    print("")
    wrap_text("The shipping manifest had the word 'water' on it, so that could only mean that the pallets you were unloading contained water. With a curious gaze, you examine the boxes closer, being reassured by a black water droplet symbol adorning each of their sides. 'Surely they wouldn't miss one bottle of water on this hot day to thank the one person who got this all to them,' you think as the angel and devil on your shoulders argue. While still contemplating your choice, your attention becomes drawn to a box that appears to be torn open. Curiosity piqued, you lean in and peer inside.")
    print("")
    wrap_text("Looking inside the opened box, you expect to see bottles of water of some kind. Instead, you see something different - a large bag filled with clear blue capsules. 'Could this be water?' you ask yourself as you look closer. This discovery strikes you as unusual, to say the least, but then you also notice the spilled capsules on the floor, the few that fell out during unloading. Your mind races with questions, and you have heard of technology that can compress water before. You think that maybe each one of these capsules was equivalent to a bottle of water, or at most, a gallon of it. You pick up a capsule and begin to think it over.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    print("You're in the right place. Now, to make the right choice.")
    print("")
    print("1. Look at the shipping manifest again.")
    print("")
    print("2. Look for water further inside of the building.")
    print("")
    print("3. Swallow one of the water capsules.")
    print("")
    choice = input("Enter the number of your choice: ")
    print("")

    if choice == '1':
        print("")
        wrap_text("After much consideration, you decide not to take one of the water capsules, no matter how thirsty you currently feel. At least not until you check the manifest first to see what these capsules are and why they were mistakenly listed as water. 'Maybe I missed something,' you think as you find and grab the clipboard. You wipe the sweat from your brow, knocking it to the page. As you begin to reread everything that you saw earlier, you notice more words on the other side of the page. Turning the sheet over, you see that these are, in fact, water, but condensed. Heavily condensed. Incredibly condensed. If you were to take one of these, you'd no longer be worrying about thirst, or much else for that matter, ever again. You gulp dryly with this new information, returning the capsule to the floor.")
        print("")
        wrap_text("You begin to carefully sweep up all of the spilled capsules inside of the warehouse, now knowing each of their values. You return them to the torn box before turning around to see if any more may have fallen out elsewhere between here and your ship. Just then, the farming robot arrives holding a bag of what appears to be loose grass and more capsules. You can't help but smile graciously at the farming robot for having the same idea as you but having already acted on it. The farming robot then deposits the bag on top of the pallet with the missing capsules before turning to face you. 'JOB COMPLETE. PLEASE FOLLOW,' the robot robotically states. You follow the robot out, glancing back briefly as the lights in the warehouse turn off and the doors begin to close behind you.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_1_1_1()
    elif choice == '2':
        print("")
        wrap_text("'This isn't my water, or whatever it is, to take,' you state honorable, placing the capsule back on the floor where you found it. 'I'm willing to bet that there's water somewhere inside that I can drink. I might even be able to find a cold glass of milk!' you think as you imagine how refreshing such a beverage would be. With those pleasant thoughts, you look around the warehouse and see a door towards the back of it. Resolving to find something to drink, you walk towards the door and open it, entering into what appears to be a dark tunnel that leads down into the earth.")
        print("")
        wrap_text("As you journey down, you notice that the architecture here is a combination of stale industrial, high technology, and just dug out dirt, a bizarre combination to say the least. As you exit the tunnel, you enter into a large poorly lit room. Beside you, you see what appears to be a light switch panel, and without a second thought, you turn on all of the light switches because why not.")
        print("")
        time.sleep(1)
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_4()
    elif choice == '3':
        print("")
        wrap_text("You look at the clear blue capsule in your hand, briefly forgetting your thirst as you consider with pride how far human civilization has come. 'In my hand do I hold an entire bottle of water. Incredible,' you think to yourself, holding the capsule towards ceiling between your fingers. You drop the capsule theatrically into your mouth and swallow it whole. And nothing happens. You wait, and still, nothing happens. Your thirst remains unquenched. Frustrated, you glance around for the manifest to see how long these water capsules are supposed to take to work. You find the clipboard and begin reading, eventually finding out that there's more to read on the back of the page. You squint briefly at the back of the sheet as you read. Your eyes widen as you read what's printed there, and then, they widen more but for another reason.")
        print("")
        print("Six months later...")
        print("")
        wrap_text("'And now, let's talk about cargo.' In a nearly empty conference room, dimly lit for viewing purposes, a training video plays against the wall from an overhead projector. On the screen, a narrator discusses the 'do's and don'ts' of managing, receiving, and delivering space cargo. '...if it's in your bay, it's here to stay! Report any damaged or leaking contents immediately to your supervisor - never eject your cargo into space just on a hunch. Next, read your shipping manifest and familiarize yourself with your cargo, getting to know all of the ins and outs of it.' The video continues by showing four people wearing jumpsuits and safety harnesses reading the documents off a pallet while nodding and smiling, discussing it amongst themselves. 'See? These guys get it!' states the narrator as the team begins to work together unloading cargo from their ship in a brief montage with a generic musical track. The video segment ends with the statement, 'Remember - read first, and then, read second!' The four people previously seen wave at the camera as the screen fades to black.")
        time.sleep(1)
        print("")
        input("Press the ENTER to continue...")
        print("")
        wrap_text("You've achieved ending 7 of 7 by quenching your thirst for water, once and for all, on Planet Caseus III. You should've quenched your thirst for knowledge first though.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        restart_game()
    else:
        print("")
        print("That doesn't appear to be an option here. I should go over all of this again.")
        print("")
        input("Press the ENTER to continue...")
        print("")
        continue_adventure_1_1()


def continue_adventure_1_1_1():
    print("")
    wrap_text("'PLEASE WAIT HERE,' the robot instructs in front of your ship. You begin fanning yourself with the clipboard, watching the robot speed away inside the building through the front entrance. Within a minute, it returns with a tray. On the tray, you see a sweating bottle of water, a printed receipt, and stapled to that receipt, a slice of cheese. You look up at the robot, partially confused but mostly grateful, grabbing the water and drinking deeply. 'THANK YOU. ENJOY THIS WATER AND FREE SAMPLE. YOU MAY LEAVE,' the robot states as it waves again, much like it did when it first approached you. You take the receipt and your cheese before entering your ship, powering up, and entering orbit. The coldness of space embraces you briefly before you begin to look for your jacket.")
    print("")
    time.sleep(1)
    input("Press the ENTER to continue...")
    print("")
    wrap_text("You've achieved ending 1 of 7, completing the delivery on Planet Caseus III without incident. Please enjoy your slice of cheese.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    restart_game()


def continue_adventure_2():
    print("")
    wrap_text("The noise stops or dies down enough for you to relax and look around - you can barely hear anything at the moment. As the dust begins to clear, surprisingly, your ship remains intact minus one cargo bay door. A lone farming robot approaches you with a piece of the door. 'UNLOADED. MADE IT SNAPPY,' the robot states robotically, but likely, in a lot of other ways too. Looking inside of the cargo bay, the pallets for this delivery are missing, likely having been unloaded somewhere inside of the building.")
    print("")
    wrap_text("With the original job now done, a new task must be done before you can leave: fix your cargo bay door. You get to it, and with the ugliest plas-weld you could've ever done, it's repaired, but now makes a horrible noise when opened or closed. You depart Planet Caseus III and hope to not soon return.")
    print("")
    time.sleep(1)
    input("Press the ENTER to continue...")
    print("")
    wrap_text("You've achieved ending 2 of 7 by completing the delivery on Planet Caseus III at the cost of one cargo bay door and some plas-weld. It's hardly noticeable.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    restart_game()


def continue_adventure_3():
    print("")
    wrap_text("In the sky, dusk can be seen beginning. 'I made great time', you think to yourself, grabbing the last pallet from your ship to unload. But as you turn and approach the building, you begin to hear a robot talking. As you approach the entrance to the warehouse, you see a robot standing outside of it with a pallet of milk in hand. 'ERROR. BLOCKED PATH,' the robot begins to repeat. You approach and see that the robot appears to be trying to put down its pallet inside of the area on the left. You don't understand what the problem is seeing as how the entire right side is empty. 'Why doesn't it just put it over there?' you wonder. But then two more robots arrive, also carrying pallets. And again, the robots begin to repeat, 'ERROR. BLOCKED PATH.' Looking back, you see dozens more robots approaching, each carrying pallets. You begin to think about the QR codes and how they may have been different after all.")
    print("")
    wrap_text("With a gnawing guilt inside, and a guiltier sweat beginning upon your brow, you slowly and calmly place the last pallet down on the right side, park the forklift where you found it, and then leave the warehouse unannounced. As you walk away, more robots arrive and begin to join the 'Choir of Error Blocked Path.' You then begin to fast walk to your ship and enter it, powering it up and leaving. You pause briefly before you mark your delivery as successful. 'I delivered what I needed to deliver. Whatever that was back there, it wasn't because of me or anything that I did. I didn't cause any of that,' you think to reassure yourself. Whatever that was back there, it's technically now someone else's problem.")
    print("")
    time.sleep(1)
    print("")
    input("Press the ENTER to continue...")
    print("")
    wrap_text("You've achieved ending 4 of 7 by completing the delivery on Planet Caseus III. You made your delivery. That's it. Nothing else happened there.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    restart_game()


def continue_adventure_4():
    print("")
    wrap_text("You freeze in horror at the sight before you, above you, and all around you. Dozens of robots are here, working, all wearing their blue overalls and straw hats. Though a pleasant and disarming look, this did nothing to dispel the sight of thousands of alien worms that they appeared to be milking. 'I was... I was wondering why I didn't see any cows up there...,' you think, trying to remain calm. Just then, one of the worms falls from the ceiling, slapping the top of your head before tumbling to the ground with the watery sound of a water balloon that failed to bust against a surface. You choke back a girlish scream as you stumble backwards into a sprint, your last clear vision being of the worm wriggling aimlessly on the ground behind you.")
    print("")
    wrap_text("You throw open the door leading into the warehouse and fall through it, briefly grabbing at the slick floor as you fall. Panting, you collect your thoughts and begin to stand, finally noticing a farming robot standing in front of you, blocking your way, holding something. Your panicked eyes finally begin to adjust, and as they do, your panic is replaced by some confusion - the robot is holding of all things, a tray.")
    print("")
    wrap_text("You carefully break eye contact with the robot to observe the tray and its contents - a bottle of water, a receipt, and a glass of milk. And almost at the sight of the milk, your stomach begins to turn, taking some color from your skin with it. You hastily grab the bottle of water and receipt and sprint to your ship. You rocket into space and swear off of 'dairy' products forever.")
    time.sleep(1)
    print("")
    input("Press the ENTER to continue...")
    print("")
    wrap_text("You've achieved ending 6 of 7 by completing the delivery on Planet Caseus III but are now burdened with knowledge that you wish you didn't have. Subterranean alien worm milk is pretty good though.")
    print("")
    input("Press the ENTER to continue...")
    print("")
    restart_game()


def restart_game():
    print("")
    print("Thanks for playing!")
    print("")
    time.sleep(1)
    input("Press the ENTER to try again...")
    intro()
    choose_destination()

choose_destination()

